name: Xcode Build

on:
  push:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'README.md'
      - 'Documentation/**'
  pull_request:
    branches: 
      - master
      - 'release/**'
    paths-ignore:
      - 'README.md'
      - 'Documentation/**'
  workflow_dispatch:

jobs:
  build-libraries:
    name: Build Libraries
    strategy:
      matrix:
        scheme:
          - SwiftPackageList
          - SwiftPackageListUI
        destination:
          - generic/platform=macOS
          - generic/platform=macOS,variant=Mac Catalyst
          - generic/platform=iOS
          - generic/platform=tvOS
          - generic/platform=watchOS
          - generic/platform=visionOS
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - name: Build Scheme
        run: |
          xcodebuild \
          -scheme ${{ matrix.scheme }} \
          -destination '${{ matrix.destination }}'
  
  test:
    name: Test
    needs: build-libraries
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - name: Install Tuist
        run: brew install tuist
      - name: Run tests
        run: |
          xcodebuild \
          -scheme SwiftPackageList-Package \
          -destination 'platform=macOS' \
          test
